import Review from "../models/reviewModel.js";
import Product from "../models/productModel.js";
import Order from "../models/orderModel.js";
import { getCache, setCache, deleteCachePattern } from "../utils/cache.js";

// Add review for a product
export const addReviewLogic = async (productId, userId, rating, comment) => {
    // Validate rating
    if (!rating || rating < 1 || rating > 5) {
        const error = new Error("Rating must be between 1 and 5");
        error.statusCode = 400;
        throw error;
    }

    // Validate product exists
    const product = await Product.findById(productId);
    if (!product) {
        const error = new Error("Product not found");
        error.statusCode = 404;
        throw error;
    }

    // Check if user purchased this product (verified purchase)
    const order = await Order.findOne({
        user: userId,
        "items.product": productId,
        $or: [{ isDelivered: true }, { orderStatus: "delivered" }],
    });
    
    // Mark review as verified if user has purchased the product
    const isVerified = !!order;

    // Check if user already reviewed this product
    const existingReview = await Review.findOne({ user: userId, product: productId });
    if (existingReview) {
        const error = new Error("You have already reviewed this product");
        error.statusCode = 400;
        throw error;
    }

    // Create review
    const review = await Review.create({
        user: userId,
        product: productId,
        rating,
        comment: comment?.trim() || "",
        isVerified,
    });

    await review.populate("user", "name");

    // Invalidate product reviews cache
    await deleteCachePattern(`productReviews:${productId}`);

    return review;
};

// Get all reviews for a product
export const getProductReviewsLogic = async (productId) => {
    // Try cache first
    const cacheKey = `productReviews:${productId}`;
    const cached = await getCache(cacheKey);
    if (cached) {
        return cached; // Returns the cached response object (includes success, data, averages)
    }

    const product = await Product.findById(productId);
    if (!product) {
        const error = new Error("Product not found");
        error.statusCode = 404;
        throw error;
    }

    const reviews = await Review.find({ product: productId })
        .populate("user", "name")
        .sort({ createdAt: -1 }).lean();

    // Calculate average rating (only verified reviews)
    const verifiedReviews = reviews.filter((r) => r.isVerified);
    const avgRating =
        verifiedReviews.length > 0
            ? (verifiedReviews.reduce((sum, review) => sum + review.rating, 0) / verifiedReviews.length).toFixed(1)
            : 0;

    const response = {
        success: true,
        data: reviews,
        averageRating: avgRating,
        totalReviews: reviews.length,
        verifiedReviews: verifiedReviews.length,
    };
    await setCache(cacheKey, response, 300); // 5 min TTL
    return response; // The controller will send this directly
};

// Delete a review (user or admin)
export const deleteReviewLogic = async (reviewId, userId, userRole) => {
    const review = await Review.findById(reviewId);
    if (!review) {
        const error = new Error("Review not found");
        error.statusCode = 404;
        throw error;
    }

    // Check authorization (owner or admin)
    if (review.user.toString() !== userId && userRole !== "admin") {
        const error = new Error("Not authorized to delete this review");
        error.statusCode = 403;
        throw error;
    }

    const productId = review.product;
    await Review.findByIdAndDelete(reviewId);

    // Invalidate product reviews cache
    await deleteCachePattern(`productReviews:${productId}`);
    // Return nothing meaningful (or success message generated by controller)
    return { productId }; // optional, not used by controller
};